tigrish/devise-i18n

- config/locales/nl.yml
`inschreven` => `ingeschreven`, seems like a typo in there.
> Fix typo for 'registration.sign_up'

- config/locales/lt.yml
Hi,
I've noticed that a lot of phrases in Lithuanian where literal translations and did not read well. This reads better.
Sorry for not doing it in the locale app, this translation file grew naturally and copy-pasting it all to the locale app would be laborious. I hope it's ok.
> Improve LT translations

- rails/locales/nl.yml
This improves the quality of the Dutch translations.
- It fixes 2 or 3 outright errors.
- Uses consistent spelling throughout (eg. "email" vs. "e-mail", "unlock" vs.
"ontgrendelen", etc).
- Uses actual Dutch words, rather than English or Dutchified English words (eg.
"fouten" instead of "errors", "vergrendeld" instead of "geunlocked", etc).
> Improve the quality of the Dutch translations

- rails/locales/de-CH.yml
swiss is supposed to be likewise the german version https://github.com/tigrish/devise-i18n/blob/master/rails/locales/de.yml#L92
> fix de-CH typo

- rails/locales/cs.yml
All the notice messages in cs locale contained  "Now you are signed in"/"Nyní jste přihlášeni." texts which are inaccurate and in some cases (when email confirm is not auto-sign-in) outright confusing.
> Cleanup :cs translations

- rails/locales/pt-BR.yml
Password reset instructions says the password won't change until you open the link 'below' but the link is above.
> Replace 'link below' with 'link above'

- rails/locales/pt-BR.yml
Fixed a typo in "pt-BR". 
The word "lembre" was incorrect. Perhaps the intent was to be "lembrete", but "redefinição" is the most appropriate here.
> Fixed pt-BR typo

- rails/locales/pt-BR.yml
In some places they were "Reinicialização de Senha" and in others it were "Redefinição de Senha".
The last appears to be more apropriate.
> Normalizing translation of 'Password Reset' to pt-BR

- rails/locales/nl.yml
Hi,
I updated the Dutch locale with a more appropriate message on failure by expanding "email" into "email address". Would it be possible to merge this into your repository? Thanks!
> Changed email to email address in failure message

- rails/locales/zh-TW.yml
In Chinese, there are two different word both means "You": 你 & 您, that could be used in the same way. However the latter one would be more formal and respectful. 
Currently in zh-TW.yml file both word exists, I suggest to replace 你 with 您.
> Unify “you” in zh-TW.yml

- rails/locales/ja.yml
The Japanese sentence ends with "。" At the end.
It is not a semicolon.
Others are doing so.
> fix ja.yml

- rails/locales/en.yml
I added the missing possible attributes, from every devise module, to the `en.yml` file. I think these are useful in many cases, e.g. an administration panel. In fact, [ActiveAdmin](https://github.com/activeadmin/activeadmin)'s default installation uses a few attributes not included before.
Should I add the missing keys to every other locale? Untranslated, of course. Although if this PR is accepted I can go ahead and translate the spanish ones :)
> Missing attributes from devise user model

- rails/locales/es-MX.yml
- rails/locales/es.yml
Follow up for #185.
I also reworded some existing translations that didn't read well and used "Email" as translation for `email` key in `es.yml`, because it is more common than `correo electrónico` and it was already used that way all over the file.
> Translate missing attributes in es locales

- rails/locales/ja.yml
- Increase in formality: Greeting change さん (san) to 様 (sama)
- Increase in formality: 良い (yoi) to よろしい (yoroshii)
- Remove "あなたの" (your) which is considered rude / sounds non-native
- Correct auto-translated Japanese (non-native) in reset_password_instructions
> JA: Various fixes

- rails/locales/ko.yml
These have been reviewed by a native speaker.
Aside from grammar fixes the only content change is to increase the formality of the greeting:
"%{recipient}님 안녕하세요!" --> "%{recipient}님". The old one was informal (Hello ___) and the new one is more formal which is safer for a more broad range of usage scenarios. Incidentally we do the same thing in Japanese with 様 (sama).
> Update content of KO translations

- rails/locales/fi.yml
- Update error strings to match devise 3.4 and up
- Stop saying 'account' when talking about 'e-mail address' (confirming the e-mail address)
- Stop calling account with 3 different words (tili, tunnus, käyttäjätunnus) - always use 'käyttäjätunnus'
- Fixed some typos and poor language (Uudelleen lähetä, Epäonnellinen)
- Add missing translations
> Update FI translations

- rails/locales/de.yml
The old message suggested that the user is already signed in. But this is not the case, as devise just unlocks the user and redirects to the sign_in path.
> Fixed de/unlocked message

- rails/locales/ko.yml
Originally removed here: https://github.com/tigrish/devise-i18n/commit/b2414aaea80c4915f88345e56f5f12ef0e0577cb
> Re-add translations ko:devise:failure:invalid and :not_found_in_database

- rails/locales/lv.yml
In latvian language interjections always should be put in commas and in these cases 'lūdzu' is used as interjection.
> Correct latvian punctuation

- rails/locales/pap-AW.yml
- rails/locales/pap-CW.yml
Papiamento is the language of the ABC-islands: Aruba, Bonaire, and Curaçao.
It's ISO 639-2 code is pap, but there are two ortographies.
pap-AW is the orhography of Aruba, and pap-CW is the one for Bonaire and Curaçao.
(In fact, pap-BQ is for Bonaire and pap-CW for Curaçao, but at this moment those two are the same and we do not us pap-BQ yet, this could change in the future).
Please add them if you would. After you add them, will they be available at 'Locale'?
Note: at this moment the two files are identical, we will start editing the pap-AW soon, but the changes are small (c=k, and such) so this pap-AW file will be a good starting point.
Thank you.
> Papiamento translations for devise

- lib/generators/devise/templates/simple_form_for/registrations/edit.html.erb
Usinng resource_name.to_s.humanize doesn't pick up translated resource name from my app's locale file - resource.model_name.human does.
> Update edit.html.erb to correctly translate resource name

- rails/locales/it.yml
I noticed some lines where "email" and "e-mail" are used together and it looks odd. I replaced "e-mail" with "email" so that the translation is more consistent. I've also added the distinction between *one* and *other* in *user* model as I saw in en.yml.
> Update locale it.yml

- rails/locales/pt.yml
I noticed that some translations were missing while I was testing my website.
Decided to translate it myself and now I'm giving it back so anyone can use.
- I've tried to remain gender neutral in some phrases.
- ~~Because the translation in this file didn't respect "Acordo Ortográfico" - I decided to follow the style, especially because this is a controversial matter and although it should be used, there are many, many people that oppose this.~~
- Went for consistency: using only "palavra-passe" for password. I replaced occurrences of "senha" (whichs is basically a synonym) with "palavra-passe" so that all dialog uses the same terminology.
- Added `one:` & `others:` to mimic the en.yml translation file.
- **UPDATE**:
- Fixed multiple typos.
- "Token" translated to "Código".
- Abide by …
> Update locale pt.yml

- rails/locales/sq.yml
Hello,
I'm submitting a reworked version for this resource. The current one is a bit awkward, due to avoidable transliterations and transcriptions (_konfirmim_, _tokeni_, _llogim_, _enkriptim_, _enkriptuar_, _lloguar_, _resetim_, _valid_, _link_, _autentifikojmë_  - all missing from the corpus of sq), conceptual errors ( locking vs blocking, receving an email vs accepting an email, attempt vs chance), and some typos. Some wording was seen necessary to make the translation flow better under sq's musicality. 
Please pull it into the master.
Regards,
Besnik
> Reworking sq translation

- rails/locales/pt-BR.yml
Change `devise.unlocks.unlocked` to be consistent with the English version:  
"Your account has been unlocked successfully. Please sign in to continue."
> Fix pt-BR Translation for unlocks.unlocked message

- rails/locales/ja.yml
- fix inconsistency
Different words (凍結 and ロック) were used to the same English word (lock).
- Minor wording
For "User", "ユーザ" is not common. Replaced with "ユーザー"
- Minor syntax mistake
Double-space question mark "？" should be used rather than "?".
End of the sentence period ("。") should not be put to email subject.
- One obvious syntax error
Usage of "の" (similar to "of" of English) was incorrect.
> fix ja.yml (fix word inconsistency and syntax mistake)

- rails/locales/de.yml
Add missing comma before "um".
More details why the comma is needed there can be found here for example: https://www.sprachschach.de/komma-vor-um/
> Fix typo in de.yml

- rails/locales/id.yml
it's been long time ago this id locale is not updated
the most irrelevant part is 
```
registration:
signed_up: Proses pendaftaran berhasil. Apabila diaktifkan, konfirmasi telah dikirimkan ke e-mail anda.
```
which means `Signed up sucessfully. If activated, email confirmation will be sent to your email`
> Update Indonesian translation

- app/views/devise/shared/_links.html.erb
by security reason, omniauth_authorize_path should be accessed via POST by default like devise 4.8.0.
https://github.com/heartcombo/devise/blob/master/CHANGELOG.md
since users who prefer GET can customize the behavior by users' side, this change should be fine.
> change omniauth_authorize_path to use POST to follow devise 4.8.0 template

- .github/workflows/ci.yml
- .travis.yml
- README.md
Since June 15th, 2021, the building on travis-ci.org is ceased. 
We can migrate to travis-ci.com, but I found this comment from https://github.com/tigrish/devise-i18n/pull/291#issuecomment-794624186.
> We're gonna have to move off of Travis as it's no longer free.
This PR migrates CI from Travis CI to GitHub Actions.
> Migrate CI from Travis CI to GitHub Actions

- Rakefile
- devise-i18n.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/devise-i18n or some tools or APIs that use the gem's metadata.
> Use https for GitHub link

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- devise-i18n.gemspec
This PR adds Ruby 3.0 and 3.1 to the CI matrix, and does the following:
* Remove Bundler from Gemfile and gemspec
* Bundler was added in #262, and GitHub Actions does not have any problem without it. 
* Update Bundler to the latest version
> Add Ruby 3.0 and 3.1 to CI matrix

- lib/generators/devise/i18n/views_generator.rb
Nice to meet you!
My name is @lef237 and I am using `devise-i18n` in Japan.
Resolved an issue where relative paths were not changed when creating Scoped views such as `rails g devise:i18n:views user`.
Specifically, the problem is related to files such as `app/views/users/passwords` and `app/views/users/confirmations/new`.
Before
```rb
<%= render "devise/shared/error_messages", resource: resource %>
```
After
```rb
<%= render "users/shared/error_messages", resource: resource %>
```
As for the code changes, I referred to the `devise` code in the following link.
[devise/views_generator.rb at main · heartcombo/devise](https://github.com/heartcombo/devise/blob/main/lib/generators/devise/views_generator.rb#L42-L50)
Sincerely.
> Problem solved with relative paths not changing when creating Scoped view.

- app/views/devise/registrations/edit.html.erb
- app/views/devise/shared/_error_messages.html.erb
- lib/devise-i18n/railtie.rb
- lib/devise-i18n/view_helpers.rb
- lib/generators/devise/templates/simple_form_for/registrations/edit.html.erb
- spec/support/devise_i18n_views_app.rb
- spec/views_spec.rb
Previously, we would always downcase the model name in the error partial. In some languages, this is not appropriate. For example, in German, nouns are always capitalized. In addition, the translated string might put the model name first, so it should still be capitalized.
There's not an elegant way to handle these kinds of rules, so we now define a helper devise_i18n_fix_model_name_case which capitalizes appropriately for the situation. The current implementation downcases in all cases, except in the error partial in German.
Fixes #260
> Handle capitalization of model name in error messages

- .github/workflows/ci.yml
This PR adds Ruby 3.2 to the CI matrix, and does the following:
- Bump actions/checkout to v3
> Add Ruby 3.2 to CI matrix

- lib/devise-i18n/railtie.rb
- spec/support/devise_i18n_views_app.rb
If a controller based on ActionController::API exists, it no longer works with devise-i18n 1.11.1.
The API does not use view helper, so I have changed it to not load it if the `helper` method is not present
```
NoMethodError:
undefined method `helper' for ActionController::API:Class
... snip ...
```
> Ignore loading helper in API-based controller

- Appraisals
- gemfiles/ruby_2.7.gemfile
- gemfiles/ruby_2.7.gemfile.lock
1.15.6 seems to not compile in GH actions
> Specify nokogiri 1.15.5 for Ruby 2.7

- devise-i18n.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/devise-i18n which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
> Provide a 'Changelog' link on rubygems.org/gems/devise-i18n
