config/locales/ko.yml

I proofread some grammatical errors.
#115

Korean translation proofreading complete

---

config/locales/ko.yml

Please refer to the commit message for detailed information of fix.
Thanks!

Fix Korean translation

---

rails/locales/cs.yml

I fixed a small typo in cs.yml. Thanks!

Fix typo in cs.yml

---

rails/locales/cs.yml

using more polite plural (according to other sentences in translation)

update of cs.yml

---

rails/locales/en.yml
rails/locales/ru.yml

Changed
```
E-mail уже подтверждена -> E-mail уже подтверждён
E-mail не найдена -> E-mail не найден
```

Fixed word ending for RU

---

rails/locales/es-MX.yml

Incorrect accents.
Acentos incorrectos

incorrect accents (es-MX)

---

rails/locales/ko.yml

I improved Korean translation. Thank you.

Improved Korean translation

---

rails/locales/ms.yml

ms is Malay
my is Burmese
https://en.wikipedia.org/wiki/Malay_language
https://en.wikipedia.org/wiki/Burmese_language
https://en.wikipedia.org/wiki/ISO_639-1

my.yml should be ms.yml

---

app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
lib/devise-i18n.rb
lib/devise-i18n/railtie.rb
lib/devise-i18n/view_helpers.rb

Also see #149.
I reverted the condition, otherwise we will have the same issue with 5.x and onwards.

Fix all mailer templates for devise4 (fixes #150)

---

rails/locales/pt-BR.yml

Adding some more translations for pt-BR previously incomplete.

Update locale for pt-BR

---

rails/locales/zh-TW.yml

Line #135 and #136 use full-width columns, so here should also use full-width columns.

Use full-width column for consistence

---

rails/locales/sq.yml

I added an sq.yml file to provide for Albanian localization.

Albanian localization

---

rails/locales/cs.yml

Credits to Christine Vasta (@kiwiistnichtda) =)

Update Czech translation

---

rails/locales/fa.yml

Update {missing} translation for Farsi/Persian

update fa locale

---

rails/locales/vi.yml

Add missing translations for vi.yml

Add missing translations for vi.yml

---

rails/locales/es.yml

Without question marks it read as an insult.

Change the tone of a translation in es

---

rails/locales/fr.yml

I'm no French teacher but it's my opinion that the literal translation of "successfully" - "avec succès" - is not idiomatic French.
I believe using the adverb "bien" (where relevant / possible) sounds more natural.

Replace "avec succès" with "bien ..."

---

rails/locales/de-CH.yml

:wave: stumbled over this when using this for a new project and having `raise_on_missing_translations` set to true :)
Thank you for this project and great to see Localeapp still doing well :)

Add missing de-CH translations

---

rails/locales/fr.yml

because it's more current to say that

Use "Email" in French instead of "Courriel"

---

rails/locales/en.yml

Added missing full stop '.' on registrations.updated_but_not_signed_in

Typo correction

---

Gemfile
Gemfile.lock
app/views/devise/registrations/edit.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
devise-i18n.gemspec
lib/generators/devise/templates/simple_form_for/registrations/edit.html.erb
spec/support/devise_i18n_views_app.rb

- https://github.com/heartcombo/devise/commit/f08e0ad24aa6fec6f585247c0465e0d46c6d8a94
- https://github.com/heartcombo/devise/commit/88625d488f43bfc804b3c63437b463e71e9211b5
- https://github.com/heartcombo/devise/commit/49ed129c4057569761278467ea2ab331223a1b80
Closes #330.
Additionally:
- Modify tests so they check devise's _error_messages.html.erb
- Adjust how the resource name is looked up in registrations/edit.html.erb to match devise's lookup

Changes for devise 4.9.0

---

app/views/devise/registrations/edit.html.erb
lib/generators/devise/templates/simple_form_for/registrations/edit.html.erb
spec/support/devise_i18n_views_app.rb

Fixes https://github.com/tigrish/devise-i18n/issues/334

Use translated value for registrations/edit heading

---

rails/locales/de.yml

Updated the German localization in the YAML file to ensure proper accurate translations.
Note: Corrections and improvements were assisted by ChatGPT-4.

update(de): correct yaml localization entries

---

rails/locales/bn.yml

This is the complete YML file of translated terms in Bangla (Bengali).

completed bn.yml file

---

rails/locales/bn.yml

Final issues fixed with proper checks

Bn typo correction

---

rails/locales/ru.yml

Corrected spelling error and added missing translation

Fix error and add translation to ru.yml
